### ISSUE TITLE
How can we replace the massive switch that routes the opcodes? is there a better way? 

### ISSUE THREAD

**Issue by santanor** [santanor/CHIP8Fun#5]

**Comment by fire-eggs** [comment]
The approach I've used in one of my projects is a "lookup" dictionary containing a delegate to invoke.
This lookup dictionary is created once and then used to direct an input value to the processing function.

So for your code, it would look something like: (pardon formatting, doing this on-the-fly)
```
// declaration
protected delegate void OpcodeFunc(short code);
protected Dictionary<short, OpcodeFunc> _opFuncs = new Dictionary<short, OpcodeFunc>();

// populate someplace (examples, incomplete)
_opFuncs.Add(0x1000, cpu._1NNN);
_opFuncs.Add(0x2000, cpu._2NNN);
...
_opFuncs.Add(0x8000, 8NNN); 
...

// DecodeOpCode then becomes:
private void DecodeOpcode(short code)
{
OpcodeFunc toRun;
if (_opFuncs.TryGetValue(code & 0xF000, out toRun)
{
toRun(code);
}
else
{
                    Debug.WriteLine($"Unknown opcode: {code:X}");
}
}
```

Note in the above that method `8NNN` is _not_ a member of `cpu`, but is a method in the class `Chip8System`. In `8NNN` you'd perform the secondary switch statement required to process the `_8XY*` opcodes. Of course, that secondary switch statement could be replaced with another dictionary...  Ditto for 0xE000, 0xF000, and 0x0000.

Kevin

**Comment by santanor** [comment]
Hey Kevin!

Thanks that would definitely make it better. Still not very sold on the idea of Dictionaries within Dictionaries though, but I guess this is what the CHIP8 opcodes give you with all those `8NNN` and `8XY*` opcodes.... It's going to be messy one way or another.

Thanks again for the idea, I like it. 
Jose

**Comment by fire-eggs** [comment]
It's not an easy problem.  

I'm not advocating a dictionary-within-a-dictionary, but multiple dictionaries. Yup, still messy tho.

If you want to try to get really clever, a more complex structure could attempt to apply the secondary masking required for (e.g.) the 8NNN opcodes:
```
struct Secondary
{
short nextMask;
short nextOp;
OpcodeFunc func;
}

_opFuncs.Add(0x1000, new Secondary {nextMask=0, nextOp=0, cpu._1NNN});
_opFuncs.Add(0x8000, new Secondary {nextMask=0x000F, nextOp=0x0000, cpu._8XY0});
_opFuncs.Add(0x8000, new Secondary {nextMask=0x000F, nextOp=0x0001, cpu._8XY1});
```
(The matching change to `DecodeOpcode` being left as an exercise for the reader)  ;-)

It becomes a question of which approach becomes harder to extend or maintain as time goes on.
And that is pretty much a personal decision ...

**Comment by santanor** [comment]
Thanks a lot Kevin. Much appreciated :D
